print("helloo world, hello world")
print("helloo world, hello world")
print("helloo world, hello world")
print("helloo world, hello world")
print("helloo world, hello world")
print("helloo world, hello world")